### ISSUE TITLE
好像不好用了

### ISSUE THREAD

**Issue by stackOverMind** [wong2/beijing_bus#6]
```
>>> from beijing_bus import BeijingBus
>>> lines = BeijingBus.get_all_lines()


```

然后，就没有然后了。hang 在那里了

先忽略---我研究一下

**Comment by wong2** [comment]
@stackOverMind 如果之前没有执行 `python mangage.py build_cache` 的话，这里会自动构建本地缓存，比较慢，表现就是卡在这里了
