### ISSUE TITLE
接口http://mc.aibaniguang/bjgj.c接口未能激活

### ISSUE THREAD

**Issue by yaohuiwu** [wong2/beijing_bus#8]
curl -H cid=1024 "http://mc.aibang.com/aiguang/bjgj.c?m=checkUpdate&version=1"
返回：
`<?xml version='1.0' encoding="utf-8"?>
<root>
    <status>502</status>
    <info>抱歉，未能激活，请退出应用，重新打开。</info>
</root>`

**Comment by yaohuiwu** [comment]
解决了。请求头中需要增加一个CID（通过抓包得到）：
`curl -H "cid:1024" -H "CID:97fbf7a1c9a80a63ed993892aaee39bba33a174ca167e2e" -v "http://mc.aibang.com/aiguang/bjgj.c?m=checkUpdate&version=77"`

但是CID如何自动获取也是个问题。

**Comment by wong2** [comment]
@yaohuiwu cid 可以随便填的：

`curl -H "cid:1024" -v "http://mc.aibang.com/aiguang/bjgj.c?m=checkUpdate&version=1"`

你之前的问题是写成了 `cid=1024`
